version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=cryptoC
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cryptoC
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
    container_name: redisdb
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-vol:/data
volumes:
  db:
    driver: local
  redis-vol:
    driver: local
